version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - /Users/luanprestes/Desktop/projects/test-generate/database:/var/lib/postgresql/data
